version: "3.7"
services:
  zookeeper:
    image: 'bitnami/zookeeper:3.7.0'
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: 'bitnami/kafka:2.8.1'
    restart: always
    depends_on:
      - zookeeper
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - 9092:9092
  backend:
    build:
      context: ./node
      dockerfile: Dockerfile 
    restart: always
    depends_on:
      - zookeeper
      - kafka
    environment:
      PORT: 3000
      kafkaHost: kafka:9092
    volumes:
      - ./node/index.js:/app/index.js
    ports:
      - 3000:3000