version: '3.8'
services:
  node_example:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
  python_example:
    build:
      context: ./python
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:3000"
  golang_example:
    build:
      context: ./go
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3002:3000"
