version: "3.8"
services:
  caching:
    image: bitnami/redis:6.0.16
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - caching
    environment:
      - REDIS_HOST=caching
    ports:
      - "3000:3000"
    volumes:
      - ./api/index.js:/app/index.js